student_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :studs
  resources :groups do 
    post 'groups/add_students' => 'groups#add_students', :as => :add_studs_group
  end
  resources :marks do
		collection do
			get 'reports'
		end
	end
  root 'studs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

student_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

student_app/app/models/group.rb
class Group < ApplicationRecord
	has_and_belongs_to_many :studs
end

student_app/app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :stud
  belongs_to :subject

  def self.calculation(mark)
	 # binding.pry	
		mark.each do |m|
			if m.subject_id == 1
				@physics_mark = m.mark * 0.30
			elsif m.subject_id == 2
				@chemistry_mark = m.mark * 0.20
			elsif m.subject_id == 3
				@maths_mark = m.mark * 0.40
			else
				@english_mark = m.mark * 0.10
			end
		end
		weighted_avg = (@physics_mark.to_f + @chemistry_mark.to_f + @maths_mark.to_f + @english_mark.to_f) / 4	
  end
end

student_app/app/models/stud.rb
class Stud < ApplicationRecord
	has_and_belongs_to_many :groups
	has_many :marks
end

student_app/app/models/subject.rb
class Subject < ApplicationRecord
	has_many :marks
end

student_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

student_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

student_app/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups=Group.all
	end

	def new
		@group=Group.new
	end

	def create
		@group=Group.new(group_params)
		if @group.save
			redirect_to @group
		else
			render 'new'
		end
	end
	
	def show
		@group=Group.find(params[:id])
	end

	def add_students
    if params[:group_id]
     	puts params
      @group = Group.find params[:group_id]
      @stud = Stud.find params[:stud][:id]
      # binding.pry
      @group.studs << @stud
      redirect_to action:'index' 		
		end
	end

	private
	def group_params
		params.require(:group).permit(:name)
	end
end

student_app/app/controllers/marks_controller.rb
class MarksController < ApplicationController
	def new
		@mark = Mark.new
	end

	def create
		respond_to do|f|
			@mark = Mark.new(mark_params)
			if @mark.save
				# redirect_to @mark
				f.html { redirect_to new_mark_path, notice: 'Mark was successfully added' }
			else
				render 'new'
			end
		end
	end

	def reports
		@student = Stud.find(params[:id])
		marks = Mark.where stud_id: @student.id
		@weighted_avg = 	Mark.calculation(marks)
	end

	private
	def mark_params
		params.require(:mark).permit(:stud_id, :subject_id, :mark)
	end
end

student_app/app/controllers/studs_controller.rb
class StudsController < ApplicationController
	def index
		@studs = Stud.all
	end
	
	def new
		@stud = Stud.new
	end

	def create
		@stud = Stud.new(stud_params)
		respond_to do|f|
			if @stud.save
				# redirect_to @stud
				# f.html { redirect_to @stud, notice: 'Student was successfully added' }
				@studs = Stud.all
				f.js {}
			else
				# render 'new'
				f.html { render 'new' }
				f.json { render json: @stud.errors, status: :unprocessable_entity}
			end
		end
	end

	def show
		@stud = Stud.find(params[:id])
	end

	def edit
	end

	def update
	end

	def delete
	end

	private
	def stud_params
		params.require(:stud).permit(:name, :email)
	end
end

student_app/app/helpers/application_helper.rb
module ApplicationHelper
end

student_app/app/helpers/groups_helper.rb
module GroupsHelper
end

student_app/app/helpers/marks_helper.rb
module MarksHelper
end

student_app/app/helpers/studs_helper.rb
module StudsHelper
end

student_app/app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
<div class="fields">
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
</div>
<div class="actions">
	<p>
		<%= f.submit %>
	</p>
</div>
<% end %>

student_app/app/views/groups/index.html.erb
<table>
	<tr>
		Name
	</tr>
	<% @groups.each do |group|%>
	<tr>
		<td><%= group.name%></td>
		<td><%= link_to 'show', group%></td>
	</tr>
	<% end %>
</table>
<%= link_to 'add_new_group', new_group_path %>
<%= link_to 'back', studs_path %>

student_app/app/views/groups/new.html.erb
<h1>Add new group</h1>
<%= render 'form' %>
<div id="list">
	<table>
		<tr>
			Name
		</tr>
		<% @groups.each do |group|%>
		<tr>
			<td><%= group.name%></td>
			<td><%= link_to 'show', group%></td>
		</tr>
		<% end %>
	</table>
</div>

student_app/app/views/groups/show.html.erb
<p> 
	<strong>Name:</strong>
	<%= @group.name %>
</p>

<p>Add Studens to Group</p>
<%= form_tag group_add_studs_group_path(@group.id) do  %> 
	<%= collection_select :stud, :id, Stud.all, :id, :name %>
	<%= submit_tag %> 
<% end %>
<%= link_to 'back', groups_path %>

student_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  	<body>
		<% if notice %>
		     	<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		     	<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		
		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
				  Logged in as <strong><%= current_user.email %></strong>.
				  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
				  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
				  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
				  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
		</p>
	  <%= yield %>
	</body>
</html>

student_app/app/views/marks/_form.html.erb
<%= form_for @mark do |f| %>
	<div class = "fields">
		<p>
			<%= f.label :student %>	
			<%= f.collection_select(:stud_id, Stud.all, :id, :name ,  {include_blank: 'Select Student'} ) %>
		</p>
		<p>
			<%= f.label :subject %>
			<%= f.collection_select(:subject_id, Subject.all, :id, :name ,  {include_blank: 'Select Student'} ) %>
		</p>
		<p>
			<%= f.label :mark %>
			<%= f.text_field :mark %>
		</p>
	</div>
	<div class = "action">
		<p>
			<%= f.submit %>
		</p>
	</div>
<% end %>

student_app/app/views/marks/new.html.erb
<h1>Add Marks</h1>
<%= render 'form' %>
<%= link_to 'back', studs_path %>

student_app/app/views/marks/reports.html.erb
<h1>Report</h1>
<p>
	<%= @student.name %>
</p>
<table border=1>
	<tr>
		<td><strong>Weighted Average: </strong> <%= @weighted_avg %></td>
	</tr>	
</table>
<%= link_to 'back', stud_path(@student.id)%>

student_app/app/views/studs/_form.html.erb
<%= form_for @stud, html: { class: 'form-horizontal', :id=>"form_id" }, remote: true do |f| %>
<div class="fields">
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email%>

	</p>
</div>
<div class="actions">
	<p>
		<%= f.submit %>
	</p>
</div>
<% end %>

student_app/app/views/studs/_list.html.erb
<h2>List of students</h2>
<p><%= link_to 'Add new student', new_stud_path %></p>
<p><%= link_to 'Show Groups', groups_path %></p>
<p><%= link_to 'Add Marks', new_mark_path %></p>
<table border=1>
	<tr>
		<th>Name</th>
		<th>Email</th>
	</tr>
	<% @studs.each do |stud| %>
		<tr>
			<td><%= stud.name %></td>
			<td><%= stud.email %></td>
			<td><%= link_to 'Show', stud %>
		</tr>
	<% end %>
</table>

student_app/app/views/studs/create.js.erb
$("#form_id").html("<%= escape_javascript(render partial: 'list') %>");

student_app/app/views/studs/index.html.erb
<h2>List of students</h2>
<p><%= link_to 'Add new student', new_stud_path %></p>
<p><%= link_to 'Show Groups', groups_path %></p>
<p><%= link_to 'Add Marks', new_mark_path %></p>
<table border=1>
	<tr>
		<th>Name</th>
		<th>Email</th>
	</tr>
	<% @studs.each do |stud| %>
		<tr>
			<td><%= stud.name %></td>
			<td><%= stud.email %></td>
			<td><%= link_to 'Show', stud %>
		</tr>
	<% end %>
</table>

student_app/app/views/studs/new.html.erb
<h1>
Add New Student
</h1>
<%= render 'form' %>	
<%= link_to 'back', studs_path %>

student_app/app/views/studs/show.html.erb
<h2>Students List </h2>
<p>
	<strong>Name: </strong>
	<%= @stud.name %>
</p>
<p>
	<strong>Email: </strong>
	<%= @stud.email %>
</p>
<%= link_to 'Show report', reports_marks_path(id:@stud.id)%>
<p>
	<%= link_to 'back', studs_path%>
</p>